name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  yamlFile:  # id of input
    description: 'Yaml file to validate'
    required: false
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
